### ISSUE TITLE
Missing concepts

### ISSUE THREAD

**Issue by EmidioStani** [catalogue-of-services-isa/SDG-model#16]
What are the concepts missing in the current SDG model proposed ?

**Comment by Marco-ICTU-NL** [comment]
at first glance I am missing:
-means of redress
-means of appeal
-rules applicable to non-reactivity
-delays
-exceptions (to procedural steps)
-authentication/identification/signatures (possible modeled as criterion requirements)
-payment methods

**Comment by barthelemyf** [comment]
Before and during the webinar, several people raised that some concepts from the SDG regulation were missing in the model proposed, such as the ones pointed out by Marco. Most of these concepts were included in the SDG concept analysis spreadsheet but were not addressed in the model. There were multiple reasons for leaving out this information such as: right balance between completeness of the model compared to the requirements of the SDGR and the complexity of the model implying more efforts to map to it or reuse it. This resulted in a certain prioritisation given to concepts relevant for 2020 which were not discussed in parallel in other groups (e.g. feedback implementation act, new version of the Core Criterion and Core Evidence Vocabulary (CCCEV) etc.).

## Proposed resolution
During the webinar, the participants asked to have:

- One SDG Data model clearly differentiating the concepts needed for the repository of links (Core model) from the concepts for providing the online procedures (Extended model). This model should be restricted to what is needed for the SDGR. All other concepts for enriching the descriptions should be described in the CPSV-AP.
- One model, CPSV-AP, for rich descriptions of catalogues of public services.

**Would this differentiation fit with the needs of the different public administrations?**
If yes, please indicate the concepts that you would like to appear in the different models. On GitHub, we propose you to use one label for the core and one label for the extended models.

## Rationale
The use cases behind the models vary from one public administration to another. Splitting the models could help better target them. 

- Core SDG model: All public administrations who must comply with the SDG would have to use this core model for sharing the information required for the repository of links (deadline of 2020 and 2022). As a core model, it would only require the strict minimum to public administrations. This targets in particular public administrations who have already extensive data models implemented, making the mapping to another data model not straightforward.
- Extended SDG model: this model should include all concepts required by the SDGR (deadline of 2023). This model will need further alignment with the OOP initiative before proposing a final version.
- CPSV-AP would fit the public administration who would like to start describing their public services digitally or would like to enrich their descriptions.

## Actions
**Public administrations**
Confirm or react on the proposition above
Indicate the concepts you are missing or your categorisation of the concepts based on the current proposition and the SDGR concept analysis (spreadsheet)
**ISA²**
The current proposition is a composition of the three models defined above with a focus on the repository of links. We will propose a new version of the core model which will be based on the mandatory concepts identified in our first proposition (concepts in red in the visualisation) addressing the other issues received.

**Comment by barthelemyf** [comment]
The discussion around this issue (core, extended models) will continue on issue #22
