### ISSUE TITLE
Objection

### ISSUE THREAD

**Issue by Eva-Christina** [catalogue-of-services-isa/SDG-model#17]
Page 10: A recap: the need for structured metadata:

Service/Title: Requesting proof of registration of birth
Event: Having a Child
Owner: Municipality? 
OBJECTION!!
Owner: PARENTS

**Comment by barthelemyf** [comment]
## Proposed resolution
We have received several comments on this example for instance about the title of the service or in this case the owner.
We will adapt the example as follows:
- Service title: Provide a birth certificate
- SDG Procedure: Requesting proof of registration of birth
- Requestor: Citizen
- Competent authority: Municipality of...

**Comment by Eva-Christina** [comment]
Thank you, this looks better!
