### ISSUE TITLE
How to model a 'Procedure' (SDGR, Annex II)

### ISSUE THREAD

**Issue by kareljanr** [catalogue-of-services-isa/SDG-model#2]
The Single Digital Gateway Regulation uses the term 'procedure' 184 times and includes the Annex II, which contains 21 procedures that should be fully digitalised by 2023. As this is a highly used concept, we propose to map this in the SDG common model. We have distinguished two approaches to do this:

1. A procedure is the same as a public service. In the CPSV-AP a public service is defined as: _A Public Service is a mandatory or discretionary set of activities performed, or able to be performed, by or on behalf of a public organisation, publicly funded and arise from public policy_ [...]

2. A procedure is a class, that is implemented by one or more public service(s).
![image](https://user-images.githubusercontent.com/47448176/67947561-31e95000-fbe4-11e9-9cec-1b882cbddb5c.png)

Other approaches could be possible. We depend on your input to identify other possible approaches or to improve the identified approaches. Feel free to provide your opinion on this issue.

**Comment by barthelemyf** [comment]
We would propose to continue the discussions on this topic on the following issue #3 .
In particular concerning the user-centricity, the combination between the class Action and the class Agent (connected with the relation "executes") should give sufficient flexibility to indicate clearly who needs to execute what regarding a specific public service. We could easily imagine to apply a filter on the Web page for displaying only the actions required from the end-user (requestor).

Regarding the specific questions in the last comment from @AGBielowski:
- The country specificity should indeed enter as from the action level or sometimes even at the public service level where countries could have different services fulfilling the same SDG procedure or information area. What is required is to agree on a similar way of structuring the information to enable its exchange and comparison between countries. So it should be generic enough to be applied by the different countries and specific enough to capture the right information. 
- In our understanding, common classifications (events, thematic areas etc.) should be used by the different countries, at least to improve the searchability. Additionally, those classifications could be mapped to the ones from the SDGR.
